from . import doctor
from . import service
from . import days_master
from . import slot
from . import patient
from . import appointment
from . import appointment_lab_line
from . import holiday
from . import res_config_settings
from . import testimonial
from . import clinic_website_settings
from . import website_menu
